### ISSUE TITLE
Not able to install jupyterlab-quickopen

### ISSUE THREAD

**Issue by Rep1AI** [jupyterlab-contrib/jupyterlab-quickopen#14]
Not able to install `jupyter labextension install @parente/jupyterlab-quickopen`

```bash
Node v13.13.0

Yarn configuration loaded.
> /opt/conda/bin/npm pack @parente/jupyterlab-quickopen
npm notice
npm notice 📦  @parente/jupyterlab-quickopen@0.5.0
npm notice === Tarball Contents ===
npm notice 1.4kB package.json
npm notice 1.5kB LICENSE
npm notice 4.2kB README.md
npm notice 245B  lib/index.d.ts
npm notice 6.4kB lib/index.js
npm notice 687B  schema/plugin.json
npm notice 62B   style/index.css
npm notice === Tarball Details ===
npm notice name:          @parente/jupyterlab-quickopen
npm notice version:       0.5.0
npm notice filename:      parente-jupyterlab-quickopen-0.5.0.tgz
npm notice package size:  5.8 kB
npm notice unpacked size: 14.5 kB
npm notice shasum:        1bf3741ee8d981dc9968ebb6a759006cb70195b3
npm notice integrity:     sha512-5PGCLraGpoELB[...]Z02Ep6T4PVSZw==
npm notice total files:   7
npm notice
parente-jupyterlab-quickopen-0.5.0.tgz

Node v13.13.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning Pattern ["@jupyterlab/celltags@file:../extensions/jupyterlab-celltags-2.1.2.tgz"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-@jupyterlab-celltags-2.1.2-e62cd0cc5f324eff9cc64d01a36315b7a5b4369e/node_modules/@jupyterlab/celltags" as pattern ["@jupyterlab/celltags@~2.1.1","@jupyterlab/celltags@^2.1.1","@jupyterlab/celltags@^2.1.1"]. This could result in non-deterministic behavior, skipping.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @jupyterlab/git@0.20.0" has unmet peer dependency "codemirror@^5.0.0".
warning "@jupyterlab/git > nbdime@6.0.0" has unmet peer dependency "codemirror@^5.0.0".
warning "keplergl-jupyter > kepler.gl > react-palm@3.2.2" has unmet peer dependency "enzyme@^3.6.0".
warning "keplergl-jupyter > kepler.gl > react-palm@3.2.2" has unmet peer dependency "enzyme-adapter-utils@^1.13.0".
warning "keplergl-jupyter > kepler.gl > react-palm@3.2.2" has unmet peer dependency "react-test-renderer@^16.4.1".
warning "keplergl-jupyter > kepler.gl > react-tooltip@3.11.6" has incorrect peer dependency "react@>=^16.0.0".
warning "keplergl-jupyter > kepler.gl > react-tooltip@3.11.6" has incorrect peer dependency "react-dom@>=^16.0.0".
warning "keplergl-jupyter > kepler.gl > react-palm > react-test-renderer@16.13.1" has incorrect peer dependency "react@^16.13.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 15.11s.

> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.87s.

> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:632
    throw err;
    ^

Error: Command failed: /opt/conda/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: null,
  signal: 'SIGKILL',
  output: [ null, null, null ],
  pid: 3337,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```

**Comment by parente** [comment]
What version of JupyterLab are you using? Are you able to install other JupyterLab extensions with the version of node you have installed?

**Comment by jtpio** [comment]
Closing since the extension can now be installed with `pip install jupyterlab-quickopen`, which should likely fix this issue.

@Rep1AI feel free to comment here or open a new issue if needed, thanks!
